# Generated by Django 3.1.3 on 2020-11-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencies',
            name='coeff',
            field=models.CharField(default='-', max_length=10, verbose_name='Коэффициент изменения'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='coeff',
            field=models.CharField(default='-', max_length=10, verbose_name='Коэффициент изменения'),
        ),
    ]
